# more information about Kubernetes Job's can be found here:
#   http://kubernetes.io/docs/user-guide/jobs/
#
# Usage:
#
#    $ kubectl apply -f plan-constructor-kubernetes-job.yaml
#    $ kubectl describe job constructor
#

apiVersion: batch/v1
kind: Job
metadata:
  name: constructor
spec:
  # depends on your actual jobs how you want to handle them
  #activeDeadlineSeconds: 30

  template:

    metadata:
      name: constructor

      annotations:

        constructionPlan: |
          internal:
            # this is necessary for Kubernetes Jobs as it would rerun the job
            # if the container exits with non-zero status code
            returnZeroOnError: true

          resources:
            cpus: 4
            memory: 4096
            disk: 10G

          input:
            - type: "git"
              source: "https://github.com/sarnowski/constructor.git"
              head: "master"
              target: "/build"

          packages:
            - make

          work:
            - cwd: "/build"
              command: "make"

    spec:
      containers:
        - name: worker
          image: sarnowski/constructor:latest
          volumeMounts:
            - name: metadata
              mountPath: /kubernetes
              readOnly: false

      volumes:
        - name: metadata
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations

      restartPolicy: Never
# TODO add secret volumes