#apiVersion: batch/v1  # TODO soon... (K8s 1.5+)
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: constructor
spec:
  template:

    metadata:
      annotations:

        constructionPlan:
          resources:
            cpus: 4
            memory: 4096
            disk: 10G

          input:
            - type: "git"
              source: "https://github.com/sarnowski/constructor.git"
              head: "master"
              target: "/build"

          packages:
            - docker.io
            - make

          work:
            - cwd: "/build"
              command: "make"

    containers:
      - name: worker
        image: sarnowski/constructor:latest
        volumeMounts:
          - name: config
            mountPath: /config
            readOnly: false

    volumes:
      - name: config
        downwardAPI:
          items:
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations

# TODO add secret volumes